src/web/CrimeTracker/CrimeTracker.Web/Models/CrimeViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CrimeTracker.Web.Models
{
    public class CrimeViewModel
    {
        public string CrimeNo { get; set; }
        public string CrimeName { get; set; }
        public string CrimeClass { get; set; }
        public string PlaceOfArrest { get; set; }
        public string ArrestingOfficer { get; set; }
        public DateTime DateOfArrest { get; set; }
    }
}

src/web/CrimeTracker/CrimeTracker.Web/Controllers/CrimesController.cs
using CrimeTracker.Core.Entities;
using CrimeTracker.Web.APIServices;
using CrimeTracker.Web.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CrimeTracker.Web.Controllers
{
    [Authorize]
    public class CrimesController : Controller
    {
        //private readonly CrimeTrackerDbContext _context;
        InternalAPI _crimeApi;
        //InternalAPI _criminalApi;
        //InternalAPI
        public CrimesController()
        {
            _crimeApi = new InternalAPI(URL.CriminalURL);
        }

        

        // GET: Crimes
        public async Task<IActionResult> Index()
        {
            string message;
            try
            {
                var urlPart = "Crimes/GetCrimes";
                
                var responseMgs = await _crimeApi.GetMessage<List<Crime>>(urlPart);
                return View(responseMgs);
            }
            catch (Exception ex)
            {

                message = "Something wrong happened";
                ViewBag.Message = message;
                throw ex;
            }
        }
        // GET: Crimes/GetCrimes?criminalNo
        public async Task<IActionResult> GetCrimes(string criminalNo)
        {
            string message;
            var user = User.Identity.Name;
            try
            {
                var urlPart = "Crimes/GetCrimes?criminalNo=" + criminalNo;

                var responseMgs = await _crimeApi.GetMessage<List<Crime>>(urlPart);
                var criminalRecords = responseMgs;


                //var urlPart = "Crimes/GetCrimes";

                //var responseMgs = await _crimeApi.GetMessage<List<Crime>>(urlPart);
                return View(responseMgs);
            }
            catch (Exception ex)
            {

                message = "Something wrong happened. " + ex.Message;
                ViewBag.Message = message;
                //throw ex;
                return View();
            }
        }

        // GET: Crimes/Details/5
        public async Task<IActionResult> Details(string criminalId)
        {


            if (criminalId == null)
            {
                return NotFound();
            }

            string message;
            try
            {
                //Retrieve criminal record based on Criminal Number
                var criminalUrlPart = "Criminals/GetCriminal?id=" + criminalId;

                var criminalResponseMgs = await _crimeApi.GetMessage<Criminal>(criminalUrlPart);
                if (criminalResponseMgs==null)
                {
                    return NotFound();
                }
                //return View(responseMgs);
                ViewBag.Criminals = criminalResponseMgs;

                //Retrieve crime record based on Criminal Number
                var crimeUrlPart = "Crimes/GetCrimes?criminalNo=" + criminalResponseMgs.criminal_no;

                var crimeResponseMgs = await _crimeApi.GetMessage<List<Crime>>(crimeUrlPart);
                //return View(responseMgs);
                ViewBag.Crimes = crimeResponseMgs;

                //Retrieve criminal Address record based on Criminal Number
                var criminalAddressUrlPart = "CriminalAddresses/GetCriminalAddresses?criminal_no=" + criminalResponseMgs.criminal_no;

                var criminalAddressResponseMgs = await _crimeApi.GetMessage<List<CriminalAddress>>(criminalAddressUrlPart);
                //return View(responseMgs);
                ViewBag.Crimes = criminalAddressResponseMgs;


            }
            catch (Exception ex)
            {

                message = "Something wrong happened";
                ViewBag.Message = message;
                throw ex;
            }

            return View();
        }

        // GET: Crimes/Create
        public IActionResult SaveCrime()
        {
            return View();
        }

        // POST: Crimes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public async Task<IActionResult> SaveCrime([FromBody] Crime crime)
        {
            var message = "";
            var successMessage = "Saved Successfully";

            try
            {
                crime.CreatedBy = User.Identity.Name;
                crime.CreatedOn = DateTime.Today;
                crime.CriminalNo = CrimeTrackerUtility.CriminalNo;
                //crime.CriminalNo = "CRM007";

                var urlPart = "Crimes/PostCrime";
                var responseMsg = await _crimeApi.PostMessage(urlPart, crime);
                var responses = responseMsg.Split('|');
                var responseMessage = responses[0].ToLower();
                //var criminalNo = responses[1];

                if (responseMessage == successMessage.ToLower())
                {
                    message = successMessage;
                    //ViewBag.Message = message;
                    return Ok(responseMessage);//RedirectToAction(nameof(Index));
                }
                return BadRequest("Something bad happened. Check and try again.");
                
            }
            catch (Exception ex)
            {
                message = "Opp Something is wrong. " + ex.Message;
                ViewBag.Message = message;
                return BadRequest("Opp Something is wrong. " + ex.Message);
            }
        }

        //FilteredItems for Datatable server-side processing
        [HttpPost]
        public async Task<JsonResult> GetFilteredItems(string criminalNo)
        {
            string errorMessage = string.Empty;
            try
            {
            //var urlPart = "Crimes/GetCrimes?criminalNo=" + CrimeTrackerUtility.CriminalNo;
            //var criminalRecords = new List<CrimeViewModel>();
            //http://localhost:30001/api/Crimes/GetCrimes?criminalNo=CRM001
                var urlPart = "Crimes/GetCrimes?criminalNo=" + criminalNo;

                var responseMgs = await _crimeApi.GetMessage<List<Crime>>(urlPart);
                var criminalRecords  = responseMgs;
                System.Threading.Thread.Sleep(2000);
                int draw = Convert.ToInt32(Request.Query["draw"]);
                if (draw < 0)
                {
                    draw = 0;
                }
                // Data to be skipped
                // if 0 first "length" records will be fetched
                //if 1 second "length" of records will be fetched.
                int start = Convert.ToInt32(Request.Query["start"]);
                if (start < 0)
                {
                    start = 0;
                }
                // records count to be fetched after skip
                int length = Convert.ToInt32(Request.Query["length"]);
                if (length < 0)
                {
                    length = 0;
                }
                //Getting sort column name
                int sortColumnIdx = Convert.ToInt32(Request.Query["order[0][column]"]);
                string sortColumnName = Request.Query["columns[" + sortColumnIdx + "][name]"];

                //Sort column direction
                string sortColumnDirection = Request.Query["order[0][dir]"];

                // search value
                string searchValue = Request.Query["search[value]"].FirstOrDefault()?.Trim();

                //Record count matching search criteria
                int recordsFilteredCount = 0;
                if (searchValue != null)
                {
                    recordsFilteredCount = criminalRecords.Where(c => c.CrimeName.Contains(searchValue)).Count();
                }
                //Total Record count
                int recordsTotalCount = criminalRecords.Count();

                //Filtered, sorted and paged data to be sent from server to view
                List<Crime> filteredData = null;
                if (sortColumnDirection == "asc")
                {
                    if (searchValue != null)
                    {
                        filteredData = criminalRecords.Where(c => c.CrimeName.Contains(searchValue))
                                                .OrderBy(c => c.GetType().GetProperty(sortColumnName).GetValue(c))
                                                .Skip(start)
                                                .Take(length)
                                                .ToList();
                    }

                }
                else
                {
                    if (searchValue != null)
                    {
                        filteredData = criminalRecords.Where(c => c.CrimeName.Contains(searchValue))
                                                .OrderByDescending(c => c.GetType().GetProperty(sortColumnName).GetValue(c))
                                                .Skip(start)
                                                .Take(length)
                                                .ToList();
                    }

                }
                if (filteredData == null)
                {
                    filteredData = criminalRecords;
                }

                //send data
                return Json(
                    new
                    {
                        data = filteredData,
                        draw = draw,
                        recordsFiltered = recordsFilteredCount,
                        recordsTotal = recordsTotalCount
                    }
                    );
            }
            catch (Exception ex)
            {
                errorMessage = "Something wrong has happened.";
                ViewBag.Message = errorMessage;
                throw ex;
            }


        }

        // GET: Crimes/Edit/5
        public async Task<ActionResult> Edit(string crimeNo)

src/web/CrimeTracker/CrimeTracker.Web/Views/Crimes/Create.cshtml
@model CrimeTracker.Core.Entities.Crime

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Crime</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CriminalNo" class="control-label"></label>
                <input asp-for="CriminalNo" class="form-control" />
                <span asp-validation-for="CriminalNo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CrimeNo" class="control-label"></label>
                <input asp-for="CrimeNo" class="form-control" />
                <span asp-validation-for="CrimeNo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CrimeName" class="control-label"></label>
                <input asp-for="CrimeName" class="form-control" />
                <span asp-validation-for="CrimeName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CrimeClass" class="control-label"></label>
                <input asp-for="CrimeClass" class="form-control" />
                <span asp-validation-for="CrimeClass" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PlaceOfArrest" class="control-label"></label>
                <input asp-for="PlaceOfArrest" class="form-control" />
                <span asp-validation-for="PlaceOfArrest" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ArrestingOfficer" class="control-label"></label>
                <input asp-for="ArrestingOfficer" class="form-control" />
                <span asp-validation-for="ArrestingOfficer" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateOfArrest" class="control-label"></label>
                <input asp-for="DateOfArrest" class="form-control" />
                <span asp-validation-for="DateOfArrest" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

src/web/CrimeTracker/CrimeTracker.Web/Views/Crimes/Delete.cshtml
@model CrimeTracker.Core.Entities.Crime

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Crime</h4>
    <hr />
    <dl class="row">
        @*<dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>*@
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CriminalNo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CriminalNo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CrimeName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CrimeName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CrimeClass)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CrimeClass)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PlaceOfArrest)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PlaceOfArrest)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ArrestingOfficer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ArrestingOfficer)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateOfArrest)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateOfArrest)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="CrimeNo" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

src/web/CrimeTracker/CrimeTracker.Web/Views/Crimes/Details.cshtml
@model CrimeTracker.Core.Entities.Crime

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Crime</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CrimeName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CrimeName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CrimeClass)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CrimeClass)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PlaceOfArrest)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PlaceOfArrest)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ArrestingOfficer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ArrestingOfficer)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateOfArrest)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateOfArrest)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.CrimeNo">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

src/web/CrimeTracker/CrimeTracker.Web/Views/Crimes/Edit.cshtml
@model CrimeTracker.Core.Entities.Crime

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Crime</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                @*<label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>*@
            </div>
            <div class="form-group">
                <label asp-for="CriminalNo" class="control-label"></label>
                <input asp-for="CriminalNo" class="form-control" />
                <span asp-validation-for="CriminalNo" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="CrimeNo" />
            <div class="form-group">
                <label asp-for="CrimeName" class="control-label"></label>
                <input asp-for="CrimeName" class="form-control" />
                <span asp-validation-for="CrimeName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CrimeClass" class="control-label"></label>
                <input asp-for="CrimeClass" class="form-control" />
                <span asp-validation-for="CrimeClass" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PlaceOfArrest" class="control-label"></label>
                <input asp-for="PlaceOfArrest" class="form-control" />
                <span asp-validation-for="PlaceOfArrest" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ArrestingOfficer" class="control-label"></label>
                <input asp-for="ArrestingOfficer" class="form-control" />
                <span asp-validation-for="ArrestingOfficer" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateOfArrest" class="control-label"></label>
                <input asp-for="DateOfArrest" class="form-control" />
                <span asp-validation-for="DateOfArrest" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

src/web/CrimeTracker/CrimeTracker.Web/Views/Crimes/GetCrimes.cshtml
@model IEnumerable<CrimeTracker.Core.Entities.Crime>

@{
    ViewData["Title"] = "GetCrimes";
}
@section AddToHead{
    <link rel="stylesheet" href="~/html/assets/vendor/jquery-datatable/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="~/html/assets/vendor/jquery-datatable/fixedeader/dataTables.fixedcolumns.bootstrap4.min.css">
    <link rel="stylesheet" href="~/html/assets/vendor/jquery-datatable/fixedeader/dataTables.fixedheader.bootstrap4.min.css">
    <link rel="stylesheet" href="~/html/assets/vendor/sweetalert/sweetalert.css" />

}
<div class="card" style="width:95%;margin:0 auto">
    <div class="card-header">
        <h5 class="card-title text-center">CRIMES</h5>
    </div>
    <div class="card-body">
        <table class="table table-condensed table-hover table-striped table-primary" id="tbl-crime">
            <thead>
                <tr>
                    <th>
                        CRIME NAME
                    </th>
                    <th>
                        CRIME CLASS
                    </th>
                    <th>
                        PLACE OF ARREST
                    </th>
                    <th>
                        ARRESTING OFFICER
                    </th>
                    <th>
                        DATE OF ARREST
                    </th>
                    <th>ACTIONS</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.CrimeName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.CrimeClass)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.PlaceOfArrest)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.ArrestingOfficer)
                        </td>
                        <td>
                            @item.DateOfArrest.ToShortDateString()
                            @*@Html.DisplayFor(modelItem => item.DateOfArrest)*@
                        </td>
                        <td>
                            <a asp-action="Edit" asp-route-id="@item.CrimeNo">Edit</a> |
                            <a asp-action="Delete" asp-route-id="@item.CrimeNo">Delete</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

@section Scripts{



    <script src="~/html/mini-sidebar/assets/bundles/datatablescripts.bundle.js"></script>
    <script src="~/html/assets/vendor/jquery-datatable/buttons/dataTables.buttons.min.js"></script>
    <script src="~/html/assets/vendor/jquery-datatable/buttons/buttons.bootstrap4.min.js"></script>
    <script src="~/html/assets/vendor/jquery-datatable/buttons/buttons.colVis.min.js"></script>
    <script src="~/html/assets/vendor/jquery-datatable/buttons/buttons.html5.min.js"></script>
    <script src="~/html/assets/vendor/jquery-datatable/buttons/buttons.print.min.js"></script>

    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js" type="text/javascript"></script>

    <!-- SweetAlert Plugin Js -->
    <script src="~/html/assets/vendor/sweetalert/sweetalert.min.js"></script>

    <script src="~/html/assets/vendor/select2/select2.min.js"></script>

    <script>

        $(document).ready(function () {
            //var oTable =
            $('#tbl-crime').DataTable({
                //"serverSide": true,
                //"bRetrieve": true,
                //"processing": true,
                //"oLanguage": { "sProcessing": "Loading... Please wait" },
                "paging": true,
                //"filter":true,
                "pageLength": 10,
                "lengthMenu": [[10, 20, 50, 100], [10, 20, 50, 100]],
                //"buttons": [
                    //'excel', 'pdf'
                //]
            });
        });
    </script>

}

src/web/CrimeTracker/CrimeTracker.Web/Views/Crimes/SaveCrime.cshtml
@model CrimeTracker.Core.Entities.Crime

@{
    ViewData["Title"] = "SaveCrime";
}
@section AddToHead{
    <link rel="stylesheet" href="~/html/assets/vendor/jquery-datatable/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="~/html/assets/vendor/jquery-datatable/fixedeader/dataTables.fixedcolumns.bootstrap4.min.css">
    <link rel="stylesheet" href="~/html/assets/vendor/jquery-datatable/fixedeader/dataTables.fixedheader.bootstrap4.min.css">
    <link rel="stylesheet" href="~/html/assets/vendor/sweetalert/sweetalert.css" />

}

<div class="row">
    <div class="col-md-1"></div>
    <div class="col-md-10">
        <div class="card">
            <div class="card-header">
                <h5 class="card-title">Add Crime Details</h5>
            </div>
            <div class="card-body">
                <div class="col-md-12">
                    <form asp-action="SaveCrime">

                        <div class="row">
                            <div class="col-md-6 col-sm-12">
                                <div class="input-group mb-3">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text input-sm" id="inputGroup-sizing-default">Crime Number</span>
                                    </div>
                                    <input type="text" class="form-control input-sm" id="crime_no" aria-label="Default" aria-describedby="inputGroup-sizing-default">
                                </div>
                            </div>
                            <div class="col-md-6 col-sm-12">
                                <div class="input-group mb-3">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text input-sm" id="inputGroup-sizing-default">Crime Name</span>
                                    </div>
                                    <input type="text" class="form-control input-sm" id="crime_name" aria-label="Default" aria-describedby="inputGroup-sizing-default">
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6 col-sm-12">
                                <div class="input-group mb-3">
                                    <div class="input-group-prepend">
                                        <label class="input-group-text">Crime Class</label>
                                    </div>
                                    <select class="custom-select" data-placeholder="Select" id="crime_class">
                                        <option>choose...</option>
                                        <option value="Male">Male</option>
                                        <option value="Female">Female</option>
                                    </select>
                                </div>
                            </div>
                            <div class="col-md-6 col-sm-12">
                                <div class="input-group mb-3">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text input-sm" id="inputGroup-sizing-default">Place of Arrest</span>
                                    </div>
                                    <input type="text" class="form-control input-sm" id="place_of_arrest" aria-label="Default" aria-describedby="inputGroup-sizing-default">
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6 col-sm-12">
                                <div class="input-group mb-3">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text input-sm" id="inputGroup-sizing-default">Arresting Officer</span>
                                    </div>
                                    <input type="text" class="form-control input-sm" id="arresting_officer" aria-label="Default" aria-describedby="inputGroup-sizing-default">
                                </div>
                            </div>
                            <div class="col-md-6 col-sm-12">
                                <div class="input-group mb-3">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text" id="inputGroup-sizing-default">Date Of Arrest</span>
                                    </div>
                                    <input type="date" class="form-control" id="date_of_arrest" aria-label="Default" aria-describedby="inputGroup-sizing-default">
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <div class="card-footer">
                <img style="display:none;" id="spinner" src="~/html/assets/vendor/select2/select2-spinner.gif" />
                <button type="button" class="btn btn-success" id="btnSave">Save</button>
            </div>
        </div>
    </div>
    <div class="col-md-1"></div>
</div>

@section Scripts{
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js" type="text/javascript"></script>

    <!-- SweetAlert Plugin Js -->
    <script src="~/html/assets/vendor/sweetalert/sweetalert.min.js"></script>

    <script src="~/html/assets/vendor/select2/select2.min.js"></script>

    <script>
    $(document).ready(function () {
        $('#btnSave').on('click', function () {

            if ($("#crime_no").val() == "") {
                    swal("Provide Crime No","Data Entry","error");
                    return;
                }

                if ($("#crime_name").val() == "") {
                    swal("Provide Crime Name","Data Entry","error");
                    return;
                }

                if ($("#crime_class").val() == "") {
                    swal("Provide Crime Class","Data Entry","error");
                    return;
                }

                //if (swal("You are about to save Crime Details. Continue ?") == true)
                //return;

                $(this).attr("disabled", true);
                $("#spinner").show();
                //Save function
                saveCrime();


        });
    })
    function saveCrime() {
        var crimeNo = $('#crime_no').val();
        var crimeName = $('#crime_name').val();
        var crimeClass = $('#crime_class').val();
        var placeOfArrest = $('#place_of_arrest').val();
        var arrestingOfficer = $('#arresting_officer').val();
        var dateOfArrest = $('#date_of_arrest').val();

        var crime = {
            CrimeNo: crimeNo,
            CrimeName: crimeName,
            CrimeClass: crimeClass,
            PlaceOfArrest: placeOfArrest,
            ArrestingOfficer: arrestingOfficer,
            DateOfArrest: dateOfArrest
        };

            $.ajax({
                type: 'POST',
                url:'@Url.Action("SaveCrime","Crimes")', //'/Crimes/SaveCrime',
                contentType: 'application/json',
                dataType: 'text',
                data:JSON.stringify(crime),
                success: function (e) {
                    //if (e == "Saved Successfully") {
                    //$('#crimeAddModal').modal('hide');
                    $("#spinner").hide();
                    swal("record saved successfully.", "Data Entry", "success");
                    $(this).attr("disabled", false);
                    //$('#crimeAddModal').modal('hide');
                    window.location.reload(true);
                    window.location.href='/CriminalAddresses/SaveCriminalAddress'
                    //}
                },
                error: function (e) {
                    swal("Error while inserting data", "Data Entry", "error");
                    $("#spinner").hide();
                    $(this).attr("disabled", false);
                }
            });


    }
    </script>

}