src/web/CrimeTracker/CrimeTracker.Web/Controllers/CriminalsController.cs
using CrimeTracker.Core.Entities;
using CrimeTracker.Web.APIServices;
using CrimeTracker.Web.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.FileProviders;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;

namespace CrimeTracker.Web.Controllers
{
    /// <summary>
    /// Criminal Controller
    /// </summary>
    [Authorize]
    public class CriminalsController : Controller
    {
        InternalAPI _criminalApi;
        /// <summary>
        /// Criminal Controller's constructor
        /// </summary>
        public CriminalsController()
        {
            _criminalApi = new InternalAPI(URL.CriminalURL);
        }
        // GET: Criminals
        public async Task<IActionResult> Index()
        {
            string message;
            try
            {
                var urlPart = "Criminals/GetCriminals";

                var responseMgs = await _criminalApi.GetMessage<List<Criminal>>(urlPart);
                return View(responseMgs);
            }
            catch (Exception)
            {

                message = "Something wrong happened";
                ViewBag.Message = message;
                return View();
            }
           
            
        }

        //FilteredItems for Datatable server-side processing
        [HttpPost]
        public async Task<JsonResult> GetFilteredItems()
        {
            string errorMessage = string.Empty;
            try
            {
                var urlPart = "Criminals/GetCriminals";

                var responseMgs = await _criminalApi.GetMessage<List<Criminal>>(urlPart);

                var criminalRecords = responseMgs;

                System.Threading.Thread.Sleep(2000);
                int draw = Convert.ToInt32(Request.Query["draw"]);
                if (draw <0)
                {
                    draw = 0;
                }
                // Data to be skipped
                // if 0 first "length" records will be fetched
                //if 1 second "length" of records will be fetched.
                int start = Convert.ToInt32(Request.Query["start"]);
                if (start <0)
                {
                    start = 0;
                }
                // records count to be fetched after skip
                int length = Convert.ToInt32(Request.Query["length"]);
                if (length <0)
                {
                    length = 0;
                }
                //Getting sort column name
                int sortColumnIdx = Convert.ToInt32(Request.Query["order[0][column]"]);
                string sortColumnName = Request.Query["columns[" + sortColumnIdx + "][name]"];

                //Sort column direction
                string sortColumnDirection = Request.Query["order[0][dir]"];

                // search value
                string searchValue = Request.Query["search[value]"].FirstOrDefault()?.Trim();

                //Record count matching search criteria
                int recordsFilteredCount = 0;
                if (searchValue !=null)
                {
                    recordsFilteredCount = criminalRecords.Where(c => c.first_name.Contains(searchValue) || c.last_name.Contains(searchValue)).Count();
                }
                //Total Record count
                int recordsTotalCount = criminalRecords.Count();

                //Filtered, sorted and paged data to be sent from server to view
                List<Criminal> filteredData = null;
                if (sortColumnDirection=="asc")
                {
                    if (searchValue != null)
                    {
                        filteredData = criminalRecords.Where(c => c.first_name.Contains(searchValue) || c.last_name.Contains(searchValue))
                                                .OrderBy(c => c.GetType().GetProperty(sortColumnName).GetValue(c))
                                                .Skip(start)
                                                .Take(length)
                                                .ToList();
                    }
                    
                }
                else
                {
                    if (searchValue !=null)
                    {
                        filteredData = criminalRecords.Where(c => c.first_name.Contains(searchValue)|| c.last_name.Contains(searchValue))
                                                .OrderByDescending(c => c.GetType().GetProperty(sortColumnName).GetValue(c))
                                                .Skip(start)
                                                .Take(length)
                                                .ToList();
                    }
                    
                }
                if (filteredData ==null)
                {
                    filteredData = criminalRecords;
                }

                //send data
                return Json(
                    new
                    {
                        data=filteredData,
                        draw=draw,
                        recordsFiltered=recordsFilteredCount,
                        recordsTotal=recordsTotalCount
                    }
                    );


            }
            catch (Exception ex)
            {
                errorMessage = "Something wrong has happened.";
                ViewBag.Message = errorMessage;
                return Json(errorMessage);
                //throw ex;
            }
            

        }
        // GET: Criminals/Details/5
        public async Task<IActionResult> Details1(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            string message;
            try
            {
                //Retrieve criminal record based on Criminal Number
                var criminalUrlPart = "Criminals/GetCriminal?id=" + id;

                var criminalResponseMgs = await _criminalApi.GetMessage<Criminal>(criminalUrlPart);
                if (criminalResponseMgs == null)
                {
                    return NotFound();
                }
                //return View(responseMgs);
                ViewBag.Criminal = criminalResponseMgs;

                //Retrieve crime record based on Criminal Number  CRM001
                var crimeUrlPart = "Crimes/GetCrimeAsync?criminalNo=" + criminalResponseMgs.criminal_no;

                var crimeResponseMgs = await _criminalApi.GetMessage<Crime>(crimeUrlPart);
                if (crimeResponseMgs==null)
                {
                    return NotFound();
                }
                //return View(responseMgs);
                ViewBag.Crimes = crimeResponseMgs;

                //Retrieve criminal Address record based on Criminal Number
                var criminalAddressUrlPart = "CriminalAddresses/GetCriminalAddresses?criminal_no=" +  criminalResponseMgs.criminal_no;

                var criminalAddressResponseMgs = await _criminalApi.GetMessage<CriminalAddress>(criminalAddressUrlPart);
                if (criminalAddressResponseMgs==null)
                {
                    return NotFound();
                }
                //return View(responseMgs);
                ViewBag.Address = criminalAddressResponseMgs;

                //Retrieve criminal History record based on Criminal Number
                var criminalHistoryUrlPart = "CriminalHistories/GetCriminalHistories?criminalNo=" +  criminalResponseMgs.criminal_no;

                var criminalHistoryResponseMgs = await _criminalApi.GetMessage<List<CriminalHistory>>(criminalHistoryUrlPart);
                if (criminalHistoryResponseMgs==null)
                {
                    return NotFound();
                }
                //return View(responseMgs);
                ViewBag.Histories = criminalHistoryResponseMgs;


            }
            catch (Exception)
            {

                message = "Something wrong happened";
                ViewBag.Message = message;
                return View();
            }

            return View();
        }

        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            string message;
            try
            {
                var status = "Current";
                var criminalNo = string.Empty;
                //Retrieve criminal record based on Criminal Number
                var criminalUrlPart = "Criminals/GetCriminal/" + id;

                var criminalResponseMgs = await _criminalApi.GetMessage<Criminal>(criminalUrlPart);
                if (criminalResponseMgs == null)
                {
                    return NotFound();
                }
                criminalNo = criminalResponseMgs.criminal_no;
                ViewBag.Criminal = criminalResponseMgs;

                //Retrieve crime record based on Criminal Number  CRM001
                //http://localhost:30001/api/Crimes/GetCrime/CRM001?status=Current
                var crimeUrlPart = "Crimes/GetCrime/" + criminalNo + "?status=" + status;

                var crimeResponseMgs = await _criminalApi.GetMessage<Crime>(crimeUrlPart);
                if (crimeResponseMgs==null)
                {
                    return NotFound();
                }
                ViewBag.Crimes = crimeResponseMgs;

                //Retrieve criminal Address record based on Criminal Number
                //http://localhost:30001/api/CriminalAddresses/GetCriminalAddress/CRM001?status=Current
                var criminalAddressUrlPart = "CriminalAddresses/GetCriminalAddress/" + criminalNo + "?status=" + status;

                var criminalAddressResponseMgs = await _criminalApi.GetMessage<CriminalAddress>(criminalAddressUrlPart);

src/web/CrimeTracker/CrimeTracker.Web/Views/Shared/_Layout.cshtml
<!doctype html>
<html lang="en">

<head>
    <title>:: CRIME TRACKER :: Home</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <meta name="description" content="Crime tracker system for nigerian police">
    <meta name="author" content="WrapTheme, design by: ThemeMakker.com">

    <link rel="icon" href="favicon.ico" type="image/x-icon">
    <!-- VENDOR CSS -->
    <link rel="stylesheet" href="~/html/assets/vendor/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/html/assets/vendor/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/html/assets/vendor/chartist/css/chartist.min.css">
    <link rel="stylesheet" href="~/html/assets/vendor/chartist-plugin-tooltip/chartist-plugin-tooltip.css">
    <link rel="stylesheet" href="~/html/assets/vendor/toastr/toastr.min.css">

    <!-- MAIN CSS -->
    <link rel="stylesheet" href="~/html/mini-sidebar/assets/css/main.css">
    <link rel="stylesheet" href="~/html/mini-sidebar/assets/css/color_skins.css">

    <link rel="stylesheet" href="~/css/site.css" />
    <link href='https://fonts.googleapis.com/css?family=Alegreya Sans' rel='stylesheet'>

    <script>
        
        function getEmployeeInfo(employeeId) {
            var emp;
            for (i = 0; i < employees.length; i++) {
                if (employees[i].EmployeeId == employeeId) {
                    emp = employees[i];
                }
            }
            return emp;
        }

        function getEmployeeByKey(key, value) {
            var emp = "";
            for (i = 0; i < employees.length; i++) {
                if (employees[i][key] === value) {
                    emp = employees[i].Name;
                }
            }
            return emp;
        }

        function camelize(str) {
            return str.replace(/(?:^\w|[A-Z]|\b\w|\s+)/g, function (match, index) {
                if (+match === 0) return ""; // or if (/\s+/.test(match)) for white spaces
                return index == 0 ? match.toLowerCase() : match.toUpperCase();
            });
        }
    </script>
    <style>

        .modal-header {
            justify-content: center !important;
            padding: 1.3rem 1rem 0.2rem 1rem !important;
            border-bottom: none;
            margin-bottom: -1rem;
            background-color: #fff;
            color: #550eb3;
        }

        .sidebar-nav .metismenu > li a {
            font-size: 13px !important;
        }

        .card {
            box-shadow: 0 1px 10px 0 rgba(0,0,0,0.1);
        }

        .input-group-text {
            font-weight: 600;
            color: #550eb3;
        }

        label {
            COLOR: #550eb3;
        }

        dt {
            COLOR: #550eb3;
        }

        /*.theme-orange:before, .theme-orange:after {
            background: #fff;
        }*/

        #left-sidebar {
            z-index: 99;
            box-shadow: 0 1px 10px 0 rgba(0,0,0,0.1);
            margin-top: -0.1rem;
            /*background-color: #fff;*/
        }

        #main-content {
            padding: 0 0 0 0.5rem;
        }

        .navbar-fixed-top {
            /*box-shadow: 0 0px 0px 0 rgba(0,0,0,0.1);*/
            width: 100%;
            margin-left: 10%;
            background-color: #f4f7f6;
        }

            .navbar-fixed-top .navbar-brand img {
                width: 100px;
                vertical-align: top;
                margin-top: 0px;
            }

        body {
            background: #fff;
            overflow-x: hidden;
            font-family: 'Alegreya Sans';
            /*font-family: Arial,Arial, Helvetica, sans-serif;*/
            color: #000 !important;
            /*line-height:0.8;*/
        }

            body:before, body:after {
                /*height: 0px;*/
            }

        .side-nav-header {
            margin-left: 3.5rem;
            color: #550eb3;
        }

        .card-header {
            background-color: #550eb3 !important;
            color: #fff;
        }

        hr {
            background-color: #550eb3
        }

        .thead-default {
            background-color: #550eb3;
            color: #fff;
        }
    </style>

    @if (IsSectionDefined("AddToHead"))
    {
        @RenderSection("AddToHead", required: false)
    }
</head>
<body class="theme-orange layout-fullwidth">

    <!-- Page Loader -->
    <div class="page-loader-wrapper">
        <div class="loader">
            <div class="m-t-30"><img src="~/html/assets/images/handcuffs-png-40842.svg" width="48" height="48" alt="Lucid"></div>
            <p>Please wait...</p>
        </div>
    </div>
    <!-- Overlay For Sidebars -->

    <div id="wrapper">

        <nav class="navbar navbar-fixed-top">
            <div class="container-fluid">
                <div class="navbar-btn">
                    <button type="button" class="btn-toggle-offcanvas"><i class="lnr lnr-menu fa fa-bars"></i></button>
                </div>

                <div class="navbar-brand">
                    <a href="@Url.Action("index","Home")">@*<img src="~/html/assets/images/handcuffs-png-40842.svg" alt="Lucid Logo" class="img-responsive logo">*@</a>
                </div>

                <div class="navbar-right">
                    <form id="navbar-search" class="navbar-form search-form">
                        <input value="" class="form-control" placeholder="Search here..." type="text">
                        <button type="button" class="btn btn-default"><i class="icon-magnifier"></i></button>
                    </form>

                    <div id="navbar-menu">
                        <ul class="nav navbar-nav">
                            <li><a href="@Url.Page("/Account/Login",new { Area="Identity"})" class="icon-menu"><i class="icon-login"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </nav>

        <div id="left-sidebar" class="sidebar mini-sidebar">
            <div class="sidebar-scroll">
                <div class="user-account">
                    <img src="~/html/assets/images/user.png" class="rounded-circle user-photo" alt="User Profile Picture">
                    <div class="dropdown">
                        <span>Welcome,</span>
                        <a href="javascript:void(0);" class="dropdown-toggle user-name" data-toggle="dropdown"><strong>@User.Identity.Name</strong></a>
                        <ul class="dropdown-menu dropdown-menu-right account animated flipInY">
                            @*<li><a href="page-profile2.html"><i class="icon-user"></i>My Profile</a></li>*@
                            @*<li><a href="javascript:void(0);"><i class="icon-settings"></i>Settings</a></li>*@
                            @*<li class="divider"></li>*@
                            <li><a href="@Url.Page("/Account/Login",new { Area="Identity"})"><i class="icon-power"></i>Logout</a></li>
                        </ul>
                    </div>
                    <hr>
                </div>
                <!-- Nav tabs -->
                <ul class="nav nav-tabs">
                    <li class="nav-item"><a class="nav-link active" data-toggle="tab" href="#criminal_menu">Criminals</a></li>
                    @*<li class="nav-item"><a class="nav-link" data-toggle="tab" href="#setting"><i class="icon-settings"></i></a></li>*@
                </ul>

                <!-- Tab panes -->
                <div class="tab-content p-l-0 p-r-0">
                    <div class="tab-pane animated fadeIn active" id="criminal_menu">
                        <nav class="sidebar-nav">
                            <ul class="main-menu metismenu">
                                <li class="active"><a href="@Url.Action("Index","Home")"><i class="icon-speedometer"></i><span>HR Dashboard</span></a></li>
                                <li><a href="#"><i class="icon-list"></i>Holidays</a></li>
                                <li><a href="#"><i class="icon-calendar"></i>Events</a></li>
                                <li><a href="#"><i class="icon-badge"></i>Activities</a></li>
                                <li>
                                    <a href="#Employees" class="has-arrow"><i class="icon-users"></i><span>Criminals</span></a>
                                    <ul>
                                        <li><a href="@Url.Action("Index","Criminals")">All Criminals</a></li>
                                        @*<li><a href="emp-leave.html">Leave Requests</a></li>
                                        <li><a href="emp-attendance.html">Attendance</a></li>
                                        <li><a href="emp-departments.html">Departments</a></li>*@
                                    </ul>
                                </li>
                                @*<li>
                                    <a href="#Authentication" class="has-arrow"><i class="icon-lock"></i><span>Authentication</span></a>
                                    <ul>
                                        <li><a href="@Url.Page("/Account/Login",new { Area="Identity"})">Login</a></li>
                                        <li><a href="@Url.Page("/Account/Register",new { Area="Identity"})">Register</a></li>
                                    </ul>
                                </li>*@
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
        </div>

        <div id="main-content">
            @RenderBody()
        </div>

    </div>

    <!-- Javascript -->
    <script src="~/html/mini-sidebar/assets/bundles/libscripts.bundle.js"></script>

    <script src="~/html/mini-sidebar/assets/bundles/vendorscripts.bundle.js"></script>

    <script src="~/html/assets/vendor/toastr/toastr.js"></script>
    <script src="~/html/mini-sidebar/assets/bundles/chartist.bundle.js"></script>
    <script src="~/html/mini-sidebar/assets/bundles/knob.bundle.js"></script> <!-- Jquery Knob-->

    <script src="~/html/mini-sidebar/assets/bundles/mainscripts.bundle.js"></script>
    <script src="~/html/mini-sidebar/assets/js/index.js"></script>

    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

src/web/CrimeTracker/CrimeTracker.Web/Views/Shared/_LayoutLogin.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <title> CRIME TRACKER :: Login</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <meta name="description" content="crime tracker. criminals database">
    <meta name="author" content="CRIME TRACKER">
    <link rel="icon" href="favicon.ico" type="image/x-icon">

    <link rel="stylesheet" href="~/html/assets/vendor/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/html/assets/vendor/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/html/assets/vendor/toastr/toastr.min.css">
    <link rel="stylesheet" href="~/html/assets/vendor/bootstrap-datepicker/css/bootstrap-datepicker3.min.css">
    <link rel="stylesheet" href="~/html/assets/css/main.css">
    <link rel="stylesheet" href="~/html/assets/css/color_skins.css">

    <style>

        body {
            background: #fff;
        }

        .card {
            border: none;
            color: rebeccapurple;
        }

        .fa-lock:before {
            content: "\f023";
            color: #fff;
        }

        .card-header {
            background-color: transparent;
            border-bottom: 1px solid rgba(0,0,0,.125);
            font-weight: bold !important;
            padding: 20px;
        }

        .validation-summary-errors {
            color: red !important
        }
    </style>
</head>
<body>
    <div class="main-content">
        @RenderBody()
    </div>
    @RenderSection("Scripts", required: false)
</body>
</html>