src/web/CrimeTracker/CrimeTracker.Web/Controllers/CriminalAddressesController.cs
using CrimeTracker.Core.Entities;
using CrimeTracker.Web.APIServices;
using CrimeTracker.Web.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CrimeTracker.Web.Controllers
{
    [Authorize]
    public class CriminalAddressesController : Controller
    {
        //private readonly CrimeTrackerDbContext _context;
        InternalAPI _criminalAddressApi;

        public CriminalAddressesController()
        {
            _criminalAddressApi=  new InternalAPI(URL.CriminalURL);
        }

        // GET: CriminalAddresses
        public async Task<IActionResult> Index()
        {
            string message;
            try
            {
                var urlPart = "CriminalAddresses/GetCriminalAddresses";

                var responseMgs = await _criminalAddressApi.GetMessage<List<CriminalAddress>>(urlPart);
                return View(responseMgs);
            }
            catch (Exception ex)
            {

                message = "Something wrong happened";
                ViewBag.Message = message;
                throw ex;
            }
        }
        public async Task<IActionResult> GetAddresses(string criminalNo)
        {
            string message;
            try
            {
                var urlPart = "CriminalAddresses/GetCriminalAddresses?criminal_no=" + criminalNo;

                var responseMgs = await _criminalAddressApi.GetMessage<List<CriminalAddress>>(urlPart);

                var criminalRecords = responseMgs;
                return View(responseMgs);
            }
            catch (Exception ex)
            {

                message = "Something wrong happened. "+ex.Message;
                ViewBag.Message = message;
                //throw ex;
                return View();
            }
        }

        //FilteredItems for Datatable server-side processing
        [HttpPost]
        public async Task<JsonResult> GetFilteredItems()
        {
            string errorMessage = string.Empty;
            try
            {
                //var urlPart = "CriminalAddresses/GetCriminalAddresses?criminalNo=" + CrimeTrackerUtility.CriminalNo;
                var criminalNo = "CRM001";
                var urlPart = "CriminalAddresses/GetCriminalAddresses?criminal_no=" + criminalNo;

                var responseMgs = await _criminalAddressApi.GetMessage<List<CriminalAddress>>(urlPart);

                var criminalRecords = responseMgs;

                System.Threading.Thread.Sleep(2000);
                int draw = Convert.ToInt32(Request.Query["draw"]);
                if (draw < 0)
                {
                    draw = 0;
                }
                // Data to be skipped
                // if 0 first "length" records will be fetched
                //if 1 second "length" of records will be fetched.
                int start = Convert.ToInt32(Request.Query["start"]);
                if (start < 0)
                {
                    start = 0;
                }
                // records count to be fetched after skip
                int length = Convert.ToInt32(Request.Query["length"]);
                if (length < 0)
                {
                    length = 0;
                }
                //Getting sort column name
                int sortColumnIdx = Convert.ToInt32(Request.Query["order[0][column]"]);
                string sortColumnName = Request.Query["columns[" + sortColumnIdx + "][name]"];

                //Sort column direction
                string sortColumnDirection = Request.Query["order[0][dir]"];

                // search value
                string searchValue = Request.Query["search[value]"].FirstOrDefault()?.Trim();

                //Record count matching search criteria
                int recordsFilteredCount = 0;
                if (searchValue != null)
                {
                    recordsFilteredCount = criminalRecords.Where(c => c.residence.Contains(searchValue)).Count();
                }
                //Total Record count
                int recordsTotalCount = criminalRecords.Count();

                //Filtered, sorted and paged data to be sent from server to view
                List<CriminalAddress> filteredData = null;
                if (sortColumnDirection == "asc")
                {
                    if (searchValue != null)
                    {
                        filteredData = criminalRecords.Where(c => c.residence.Contains(searchValue))
                                                .OrderBy(c => c.GetType().GetProperty(sortColumnName).GetValue(c))
                                                .Skip(start)
                                                .Take(length)
                                                .ToList();
                    }

                }
                else
                {
                    if (searchValue != null)
                    {
                        filteredData = criminalRecords.Where(c => c.residence.Contains(searchValue))
                                                .OrderByDescending(c => c.GetType().GetProperty(sortColumnName).GetValue(c))
                                                .Skip(start)
                                                .Take(length)
                                                .ToList();
                    }

                }
                if (filteredData == null)
                {
                    filteredData = criminalRecords;
                }

                //send data
                return Json(
                    new
                    {
                        data = filteredData,
                        draw = draw,
                        recordsFiltered = recordsFilteredCount,
                        recordsTotal = recordsTotalCount
                    }
                    );
            }
            catch (Exception ex)
            {
                errorMessage = "Something wrong has happened.";
                ViewBag.Message = errorMessage;
                throw ex;
            }


        }

        // GET: CriminalAddresses/Details/5
        public ActionResult Details(int? id)
        {
            //if (id == null)
            //{
            //    return NotFound();
            //}

            //var criminalAddress = await _context.CriminalAddresses
            //    .FirstOrDefaultAsync(m => m.id == id);
            //if (criminalAddress == null)
            //{
            //    return NotFound();
            //}

            //return View(criminalAddress);
            return View(id);
        }

        //GET: CriminalAddresses/Create
        public IActionResult SaveCriminalAddress()
        {
            return View();
        }

        // POST: CriminalAddresses/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public async Task<IActionResult> SaveCriminalAddress([FromBody] CriminalAddress criminalAddress)
        {
            var message = "";
            var successMessage = "Saved Successfully";

            try
            {
                criminalAddress.CreatedBy = User.Identity.Name;
                criminalAddress.CreatedOn = DateTime.Today;
                criminalAddress.criminal_no = CrimeTrackerUtility.CriminalNo;
                //criminalAddress.criminal_no = "CRM005";// CrimeTrackerUtility.CriminalNo;

                var urlPart = "CriminalAddresses/PostCriminalAddress";
                var responseMsg = await _criminalAddressApi.PostMessage(urlPart, criminalAddress);
                var responses = responseMsg.Split('|');
                var responseMessage = responses[0].ToLower();
                var criminalNo = responses[1];

                if (responseMessage == successMessage.ToLower())
                {
                    message = successMessage;
                    return Ok(responseMessage);
                }
                return BadRequest("Something bad happened. Check and try again.");
                
            }
            catch (Exception ex)
            {
                message = "Opp Something is wrong. " + ex.Message;
                ViewBag.Message = message;
                return BadRequest("Opp Something is wrong. " + ex.Message);
            }
        }

        // GET: CriminalAddresses/Edit/5
        public ActionResult Edit(int? id)
        {
            //if (id == null)
            //{
            //    return NotFound();
            //}

            //var criminalAddress = await _context.CriminalAddresses.FindAsync(id);
            //if (criminalAddress == null)
            //{
            //    return NotFound();
            //}
            //return View(criminalAddress);
            return View(id);
        }

        // POST: CriminalAddresses/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id,  CriminalAddress criminalAddress)
        {
            if (id != criminalAddress.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                //try
                //{
                //    _context.Update(criminalAddress);
                //    await _context.SaveChangesAsync();
                //}
                //catch (DbUpdateConcurrencyException)
                //{
                //    if (!CriminalAddressExists(criminalAddress.id))
                //    {
                //        return NotFound();
                //    }
                //    else
                //    {

src/web/CrimeTracker/CrimeTracker.Web/Views/CriminalAddresses/Delete.cshtml
@model CrimeTracker.Core.Entities.CriminalAddress

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CriminalAddress</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.criminal_no)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.criminal_no)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.residence)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.residence)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.phone_no)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.phone_no)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.state)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.state)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.lgc)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.lgc)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.city)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.city)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

src/web/CrimeTracker/CrimeTracker.Web/Views/CriminalAddresses/Details.cshtml
@model CrimeTracker.Core.Entities.CriminalAddress

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>CriminalAddress</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.criminal_no)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.criminal_no)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.residence)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.residence)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.phone_no)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.phone_no)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.state)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.state)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.lgc)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.lgc)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.city)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.city)
        </dd>
        
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

src/web/CrimeTracker/CrimeTracker.Web/Views/CriminalAddresses/Edit.cshtml
@model CrimeTracker.Core.Entities.CriminalAddress

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>CriminalAddress</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="id" />
            <div class="form-group">
                <label asp-for="criminal_no" class="control-label"></label>
                <input asp-for="criminal_no" class="form-control" />
                <span asp-validation-for="criminal_no" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="residence" class="control-label"></label>
                <input asp-for="residence" class="form-control" />
                <span asp-validation-for="residence" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="phone_no" class="control-label"></label>
                <input asp-for="phone_no" class="form-control" />
                <span asp-validation-for="phone_no" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="email" class="control-label"></label>
                <input asp-for="email" class="form-control" />
                <span asp-validation-for="email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="state" class="control-label"></label>
                <input asp-for="state" class="form-control" />
                <span asp-validation-for="state" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="lgc" class="control-label"></label>
                <input asp-for="lgc" class="form-control" />
                <span asp-validation-for="lgc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="city" class="control-label"></label>
                <input asp-for="city" class="form-control" />
                <span asp-validation-for="city" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <input type="submit" value="Update" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

src/web/CrimeTracker/CrimeTracker.Web/Views/CriminalAddresses/GetAddresses.cshtml
@model IEnumerable<CrimeTracker.Core.Entities.CriminalAddress>

@{
    ViewData["Title"] = "GetAddresses";
}
@section AddToHead{
    <link rel="stylesheet" href="~/html/assets/vendor/jquery-datatable/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="~/html/assets/vendor/jquery-datatable/fixedeader/dataTables.fixedcolumns.bootstrap4.min.css">
    <link rel="stylesheet" href="~/html/assets/vendor/jquery-datatable/fixedeader/dataTables.fixedheader.bootstrap4.min.css">
    <link rel="stylesheet" href="~/html/assets/vendor/sweetalert/sweetalert.css" />

}

<div class="card" style="width:95%;margin:0 auto">
    <div class="card-header">
        <h5 class="card-title text-center">ADDRESSES</h5>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-condensed table-hover table-striped" id="tbl-address">
                <thead>
                    <tr>
                        <th>
                            RESIDENCE
                        </th>
                        <th>
                            PHONE NUMBER
                        </th>
                        <th>
                            EMAIL ADDRESS
                        </th>
                        <th>
                            STATE OF ORIGIN
                        </th>
                        <th>
                            LGC
                        </th>
                        <th>
                            CITY
                        </th>
                        <th>ACTIONS</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.residence)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.phone_no)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.email)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.state)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.lgc)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.city)
                            </td>
                            <td>
                                <a asp-action="Edit" asp-route-id="@item.id">Edit</a> |
                                <a asp-action="Delete" asp-route-id="@item.id">Delete</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

@section Scripts{



    <script src="~/html/mini-sidebar/assets/bundles/datatablescripts.bundle.js"></script>
    <script src="~/html/assets/vendor/jquery-datatable/buttons/dataTables.buttons.min.js"></script>
    <script src="~/html/assets/vendor/jquery-datatable/buttons/buttons.bootstrap4.min.js"></script>
    <script src="~/html/assets/vendor/jquery-datatable/buttons/buttons.colVis.min.js"></script>
    <script src="~/html/assets/vendor/jquery-datatable/buttons/buttons.html5.min.js"></script>
    <script src="~/html/assets/vendor/jquery-datatable/buttons/buttons.print.min.js"></script>

    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js" type="text/javascript"></script>

    <!-- SweetAlert Plugin Js -->
    <script src="~/html/assets/vendor/sweetalert/sweetalert.min.js"></script>

    <script src="~/html/assets/vendor/select2/select2.min.js"></script>

    <script>

        $(document).ready(function () {
            //var oTable =
            $('#tbl-address').DataTable({
                //"serverSide": true,
                //"bRetrieve": true,
                //"processing": true,
                //"oLanguage": { "sProcessing": "Loading... Please wait" },
                "paging": true,
                //"filter":true,
                "pageLength": 10,
                "lengthMenu": [[10, 20, 50, 100], [10, 20, 50, 100]],
                //"buttons": [
                   // 'excel', 'pdf'
                //]
            });
        });
    </script>

}

src/web/CrimeTracker/CrimeTracker.Web/Views/CriminalAddresses/SaveCriminalAddress.cshtml
@model CrimeTracker.Core.Entities.CriminalAddress

@{
    ViewData["Title"] = "Create";
}
@section AddToHead{
    <link rel="stylesheet" href="~/html/assets/vendor/jquery-datatable/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="~/html/assets/vendor/jquery-datatable/fixedeader/dataTables.fixedcolumns.bootstrap4.min.css">
    <link rel="stylesheet" href="~/html/assets/vendor/jquery-datatable/fixedeader/dataTables.fixedheader.bootstrap4.min.css">
    <link rel="stylesheet" href="~/html/assets/vendor/sweetalert/sweetalert.css" />

}
<div class="row">
    <div class="col-md-1"></div>
    <div class="col-md-10">
        <div class="card">
            <div class="card-header">
                <h5 class="card-title text-lg-center">Criminal Address</h5>
            </div>
            <div class="card-body">
                <div class="col-md-12">
                    <form asp-action="SaveCriminalAddress">

                        <div class="row">
                            <div class="col-md-6 col-sm-12">
                                <div class="input-group mb-3">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text input-sm" id="inputGroup-sizing-default">Residence</span>
                                    </div>
                                    <input type="text" class="form-control input-sm" id="residence" aria-label="Default" aria-describedby="inputGroup-sizing-default">
                                </div>
                            </div>
                            <div class="col-md-6 col-sm-12">
                                <div class="input-group mb-3">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text"><i class="fa fa-mobile-phone"></i></span>
                                    </div>
                                    <input type="text" id="phone_no" class="form-control mobile-phone-number" placeholder="Ex: +000 (000) 0000-00-00">
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6 col-sm-12">
                                <div class="input-group mb-3">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text"><i class="fa fa-envelope-o"></i></span>
                                    </div>
                                    <input type="text" id="email" class="form-control email" placeholder="Ex: example@example.com">
                                </div>
                            </div>
                            <div class="col-md-6 col-sm-12">
                                <div class="input-group mb-3">
                                    <div class="input-group-prepend">
                                        <label class="input-group-text">State</label>
                                    </div>
                                    <select class="custom-select" data-placeholder="Select" id="state">
                                        <option>choose...</option>
                                        <option value="Abuja">FCT</option>
                                        <option value="Nasarawa">Nasarawa</option>
                                        <option value="Lagos">Lagos</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6 col-sm-12">
                                <div class="input-group mb-3">
                                    <div class="input-group-prepend">
                                        <label class="input-group-text">LGC</label>
                                    </div>
                                    <select class="custom-select" data-placeholder="Select" id="lgc">
                                        <option>choose...</option>
                                        <option value="Kuje">Kuje</option>
                                        <option value="Toto">Toto</option>
                                        <option value="Ikeja">Ikeja</option>
                                    </select>
                                </div>
                            </div>
                            <div class="col-md-6 col-sm-12">
                                <div class="input-group mb-3">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text input-sm" id="inputGroup-sizing-default">City</span>
                                    </div>
                                    <input type="text" class="form-control input-sm" id="city" aria-label="Default" aria-describedby="inputGroup-sizing-default">
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <div class="card-footer">
                <img style="display:none;" id="spinner" src="~/html/assets/vendor/select2/select2-spinner.gif" />
                <button type="button" class="btn btn-success" id="btnSave">Save</button>
            </div>
        </div>
    </div>
    <div class="col-md-1"></div>
</div>

@section Scripts{
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js" type="text/javascript"></script>

    <!-- SweetAlert Plugin Js -->
    <script src="~/html/assets/vendor/sweetalert/sweetalert.min.js"></script>

    <script src="~/html/assets/vendor/select2/select2.min.js"></script>

    <script>
        $(document).ready(function () {
            $('#btnSave').on('click', function () {

                if ($("#residence").val() == "") {
                    swal("Provide residence", "Data Entry", "error");
                    //alert("Provide residence");
                    return;
                }

                if ($("#phone_no").val() == "") {
                    swal("Provide Phone Number", "Data Entry", "error");
                    //alert("Provide Phone Number");
                    return;
                }

                if ($("#email").val() == "") {
                    swal("Provide Email Address", "Data Entry", "error");
                    //alert("Provide Email Address");
                    return;
                }

                $(this).attr("disabled", true);
                $("#spinner").show();

                saveAddress();

            });
        })
        //Save Address
        function saveAddress() {

            var residence = $('#residence').val();
            var phone = $('#phone_no').val();
            var email = $('#email').val();
            var state = $('#state').val();
            var lgc = $('#lgc').val();
            var city = $('#city').val();

            var address = {
                residence: residence,
                phone_no: phone,
                email: email,
                state: state,
                lgc: lgc,
                city: city
            };

            $.ajax({
                type: 'POST',
                url:'@Url.Action("SaveCriminalAddress","CriminalAddresses")', //'/CriminalAddresses/SaveCriminalAddress',
                contentType: 'application/json',
                dataType:'text',
                data: JSON.stringify(address),
                //cache: false,
                //processData: false,
                //contentType:false,
                success: function (e) {

                    $("#spinner").hide();
                    $(this).attr("disabled", false);
                    //$('#AddressAddModal').modal('hide');
                    window.location.href='/criminals/index'//(true);
                    //}
                },
                error: function (e) {
                    swal("Error while inserting data", "Data Entry", "error");
                    $("#spinner").hide();
                    $(this).attr("disabled", false);
                }
            });
        };
    </script>

}